sudo apt purge -y aspnetcore-runtime-2.1 
sudo apt purge -y aspnetcore-runtime-3.1 
sudo apt purge -y aspnetcore-runtime-5.0 
sudo apt purge -y aspnetcore-runtime-6.0 
sudo apt purge -y aspnetcore-targeting-pack-3.1
sudo apt purge -y aspnetcore-targeting-pack-5.0
sudo apt purge -y aspnetcore-targeting-pack-6.0
sudo apt purge -y cpp-10 
sudo apt purge -y cpp 
sudo apt purge -y curl
sudo apt purge -y dnsmasq-base
sudo apt purge -y dnsutils-security
sudo apt purge -y docker-buildx-plugin
sudo apt purge -y docker-ce-cli 
sudo apt purge -y docker-ce-rootless-extras 
sudo apt purge -y docker-ce 
sudo apt purge -y docker-compose-plugin 
sudo apt purge -y dotnet-apphost-pack-3.1 
sudo apt purge -y dotnet-apphost-pack-5.0 
sudo apt purge -y dotnet-apphost-pack-6.0 
sudo apt purge -y dotnet-host  
sudo apt purge -y dotnet-hostfxr-2.1 
sudo apt purge -y dotnet-hostfxr-3.1 
sudo apt purge -y dotnet-hostfxr-5.0 
sudo apt purge -y dotnet-hostfxr-6.0 
sudo apt purge -y dotnet-runtime-2.1 
sudo apt purge -y dotnet-runtime-3.1 
sudo apt purge -y dotnet-runtime-5.0 
sudo apt purge -y dotnet-runtime-6.0 
sudo apt purge -y dotnet-runtime-deps-2.1
sudo apt purge -y dotnet-runtime-deps-3.1
sudo apt purge -y dotnet-runtime-deps-5.0
sudo apt purge -y dotnet-runtime-deps-6.0
sudo apt purge -y dotnet-sdk-6.0 
sudo apt purge -y dotnet-targeting-pack-3.1 
sudo apt purge -y dotnet-targeting-pack-5.0 
sudo apt purge -y dotnet-targeting-pack-6.0 
sudo apt purge -y emacs-bin-common-security 
sudo apt purge -y emacs-common-security 
sudo apt purge -y emacs-nox-security 
sudo apt purge -y emacsen-common 
sudo apt purge -y g++-10   
sudo apt purge -y g++ 
sudo apt purge -y gcc-10-base 
sudo apt purge -y gcc-10   
sudo apt purge -y gcc-9-base
sudo apt purge -y gcc 
sudo apt purge -y gcsfuse
sudo apt purge -y gdb 
sudo apt purge -y git
sudo apt purge -y gnupg-l10n 
sudo apt purge -y gnupg-utils 
sudo apt purge -y gnupg2 
sudo apt purge -y gnupg 
sudo apt purge -y google-cloud-sdk-app-engine-go
sudo apt purge -y google-cloud-sdk-app-engine-java
sudo apt purge -y google-cloud-sdk-app-engine-python-extras
sudo apt purge -y google-cloud-sdk-app-engine-python
sudo apt purge -y google-cloud-sdk-bigtable-emulator
sudo apt purge -y google-cloud-sdk-cbt
sudo apt purge -y google-cloud-sdk-cloud-build-local
sudo apt purge -y google-cloud-sdk-cloud-run-proxy
sudo apt purge -y google-cloud-sdk-datastore-emulator
sudo apt purge -y google-cloud-sdk-gke-gcloud-auth-plugin
sudo apt purge -y google-cloud-sdk-kpt
sudo apt purge -y google-cloud-sdk-local-extract
sudo apt purge -y google-cloud-sdk-minikube
sudo apt purge -y google-cloud-sdk-nomos
sudo apt purge -y google-cloud-sdk-package-go-module
sudo apt purge -y google-cloud-sdk-pubsub-emulator
sudo apt purge -y google-cloud-sdk-skaffold
sudo apt purge -y google-cloud-sdk
sudo apt purge -y gpg-agent
sudo apt purge -y gpg-wks-client
sudo apt purge -y gpg-wks-server
sudo apt purge -y gpg 
sudo apt purge -y gpgconf 
sudo apt purge -y gpgsm 
sudo apt purge -y gpgv 
sudo apt purge -y graphviz 2.42.2-5  
sudo apt purge -y grep 3.6-1+deb11u1  
sudo apt purge -y kubectl
sudo apt purge -y lxc 1:4.0.6-2+deb11u2  
sudo apt purge -y lynx-common 
sudo apt purge -y lynx 
sudo apt purge -y m4 
sudo apt purge -y mailcap
sudo apt purge -y make 
sudo apt purge -y mercurial-common 
sudo apt purge -y mercurial 
sudo apt purge -y mysql-apt-config
sudo apt purge -y mysql-client
sudo apt purge -y mysql-common
sudo apt purge -y mysql-community-client-core
sudo apt purge -y mysql-community-client-plugins
sudo apt purge -y mysql-community-client
sudo apt purge -y openjdk-11-jdk-headless
sudo apt purge -y openjdk-11-jdk
sudo apt purge -y openjdk-11-jre-headless
sudo apt purge -y openjdk-11-jre
sudo apt purge -y openjdk-17-jdk-headless-security  
sudo apt purge -y openjdk-17-jdk-security  
sudo apt purge -y openjdk-17-jre-headless-security  
sudo apt purge -y openjdk-17-jre-security  
sudo apt purge -y perl-base 
sudo apt purge -y perl-modules-5.32 
sudo apt purge -y perl 
sudo apt purge -y php-common 
sudo apt purge -y php-pear 
sudo apt purge -y php7.4-bcmath 
sudo apt purge -y php7.4-cgi 
sudo apt purge -y php7.4-cli 
sudo apt purge -y php7.4-common 
sudo apt purge -y php7.4-dev 
sudo apt purge -y php7.4-json 
sudo apt purge -y php7.4-mbstring 
sudo apt purge -y php7.4-mysql 
sudo apt purge -y php7.4-opcache 
sudo apt purge -y php7.4-readline 
sudo apt purge -y php7.4-xml 
sudo apt purge -y postgresql-15-pgdg 
sudo apt purge -y postgresql-client-15-pgdg 
sudo apt purge -y postgresql-client-common-pgdg 
sudo apt purge -y postgresql-client-pgdg 
sudo apt purge -y postgresql-common-pgdg 
sudo apt purge -y postgresql-pgdg 
sudo apt purge -y powershell 
sudo apt purge -y python-apt-common 
sudo apt purge -y python-pip-whl 
sudo apt purge -y python-pkg-resources 
sudo apt purge -y python-setuptools 
sudo apt purge -y python2-minimal 
sudo apt purge -y python2.7-dev 
sudo apt purge -y python2.7-minimal 
sudo apt purge -y python2.7 
sudo apt purge -y python2 
sudo apt purge -y python3-apt 
sudo apt purge -y python3-dbus 
sudo apt purge -y python3-distutils 
sudo apt purge -y python3-gi 
sudo apt purge -y python3-lib2to3 
sudo apt purge -y python3-minimal 
sudo apt purge -y python3-pip 
sudo apt purge -y python3-pkg-resources
sudo apt purge -y python3-pycurl 
sudo apt purge -y python3-setuptools
sudo apt purge -y python3-software-properties
sudo apt purge -y python3-venv 
sudo apt purge -y python3-wheel 
sudo apt purge -y python3.9-dev 
sudo apt purge -y python3.9-minimal 
sudo apt purge -y python3.9-venv 
sudo apt purge -y python3.9 
sudo apt purge -y python3 
sudo apt purge -y qemu-user-static
sudo apt purge -y qemu-user
sudo apt purge -y ruby-dev 
sudo apt purge -y ruby-minitest 
sudo apt purge -y ruby-net-telnet 
sudo apt purge -y ruby-power-assert 
sudo apt purge -y ruby-rubygems 
sudo apt purge -y ruby-test-unit 
sudo apt purge -y ruby-xmlrpc 
sudo apt purge -y ruby2.7-dev 
sudo apt purge -y ruby2.7 
sudo apt purge -y ruby 
sudo apt purge -y rubygems-integration 
sudo apt purge -y sqlite3   
sudo apt purge -y telnet 
